"use client";
import {FormEvent,useEffect,useState} from "react";
import AppShell from "@/components/AppShell";
import {supabase} from "@/lib/supabase";

type Opt={id:string;name:string};
type Recipe={id:string;product_id:string;yield_quantity:number;expected_loss:number;active:boolean};
type Order={id:string;recipe_id:string;produced_quantity:number;status:string;production_date:string};
export default function Producao(){
 const[products,setProducts]=useState<Opt[]>([]),[items,setItems]=useState<Opt[]>([]),[recipes,setRecipes]=useState<Recipe[]>([]),[orders,setOrders]=useState<Order[]>([]);const[productId,setProductId]=useState(""),[yieldQty,setYieldQty]=useState(1),[loss,setLoss]=useState(0),[ingredientId,setIngredientId]=useState(""),[ingredientQty,setIngredientQty]=useState(1),[recipeId,setRecipeId]=useState(""),[produced,setProduced]=useState(1),[msg,setMsg]=useState(""),[erro,setErro]=useState("");
 async function load(){const[p,i,r,o]=await Promise.all([supabase.from("erp_products").select("id,name").eq("active",true).eq("origin","produced").order("name"),supabase.from("erp_stock_items").select("id,name").eq("active",true).order("name"),supabase.from("erp_recipes").select("id,product_id,yield_quantity,expected_loss,active").eq("active",true).order("created_at",{ascending:false}),supabase.from("erp_production_orders").select("id,recipe_id,produced_quantity,status,production_date").order("production_date",{ascending:false}).limit(100)]);const f=p.error||i.error||r.error||o.error;if(f)throw f;setProducts((p.data??[]) as Opt[]);setItems((i.data??[]) as Opt[]);setRecipes((r.data??[]) as Recipe[]);setOrders((o.data??[]) as Order[])}
 useEffect(()=>{load().catch(e=>setErro(e.message))},[]);
 async function createRecipe(e:FormEvent){e.preventDefault();setErro("");const{data:r,error}=await supabase.from("erp_recipes").insert({product_id:productId,yield_quantity:yieldQty,expected_loss:loss}).select("id").single();if(error){setErro(error.message);return}const x=await supabase.from("erp_recipe_items").insert({recipe_id:r.id,stock_item_id:ingredientId,quantity:ingredientQty});if(x.error)setErro(x.error.message);else{setMsg("Ficha técnica criada.");setRecipeId(r.id);await load()}}
 async function complete(e:FormEvent){e.preventDefault();setErro("");const{error}=await supabase.rpc("erp_complete_production",{p_recipe_id:recipeId,p_produced_quantity:produced,p_notes:null});if(error)setErro(error.message);else{setMsg("Produção concluída: insumos baixados e produto pronto adicionado ao estoque.");await load()}}
 const pname=(id:string)=>products.find(x=>x.id===id)?.name??"Produto";
 return <AppShell><div className="topbar"><div><h1>Produção</h1><div className="subtitle">Somente a Matriz pode concluir ordens de produção.</div></div></div>{erro&&<div className="notice error">{erro}</div>}{msg&&<div className="notice success">{msg}</div>}
 <form className="form-card" onSubmit={createRecipe}><h2>Nova ficha técnica</h2><div className="form-grid"><label>Produto produzido<select required value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Selecione</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Rendimento<input type="number" min="0.001" step="0.001" value={yieldQty} onChange={e=>setYieldQty(Number(e.target.value))}/></label><label>Perda esperada (%)<input type="number" min="0" step="0.01" value={loss} onChange={e=>setLoss(Number(e.target.value))}/></label><label>Ingrediente principal<select required value={ingredientId} onChange={e=>setIngredientId(e.target.value)}><option value="">Selecione</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Quantidade do ingrediente<input type="number" min="0.001" step="0.001" value={ingredientQty} onChange={e=>setIngredientQty(Number(e.target.value))}/></label></div><div className="actions"><button className="button">Criar ficha</button></div></form>
 <form className="form-card" onSubmit={complete}><h2>Concluir produção</h2><div className="form-grid"><label>Ficha técnica<select required value={recipeId} onChange={e=>setRecipeId(e.target.value)}><option value="">Selecione</option>{recipes.map(r=><option key={r.id} value={r.id}>{pname(r.product_id)} · rendimento {r.yield_quantity}</option>)}</select></label><label>Quantidade produzida<input type="number" min="0.001" step="0.001" value={produced} onChange={e=>setProduced(Number(e.target.value))}/></label></div><div className="actions"><button className="button">Concluir produção</button></div></form>
 <section className="section"><div className="section-head"><h2>Ordens concluídas</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Ficha</th><th>Quantidade</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{new Date(o.production_date+"T12:00:00").toLocaleDateString("pt-BR")}</td><td>{o.recipe_id.slice(0,8)}</td><td>{Number(o.produced_quantity).toFixed(3)}</td><td>{o.status}</td></tr>)}</tbody></table>{!orders.length&&<div className="empty">Nenhuma produção registrada.</div>}</div></section></AppShell>
}
