"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import AppShell from "@/components/AppShell";
import {supabase} from "@/lib/supabase";

type Unit={id:string;name:string;type:string};
type Item={id:string;name:string;item_type:string;unit_measure:string;minimum_stock:number;average_cost:number};
type Move={id:string;unit_id:string;item_id:string;movement_type:string;quantity:number;movement_date:string};
const incoming=new Set(["purchase","production_output","adjustment","transfer_in","inventory"]);
export default function Estoque(){
 const[units,setUnits]=useState<Unit[]>([]),[items,setItems]=useState<Item[]>([]),[moves,setMoves]=useState<Move[]>([]);const[name,setName]=useState(""),[itemType,setItemType]=useState("resale"),[measure,setMeasure]=useState("UN"),[min,setMin]=useState(0),[cost,setCost]=useState(0);const[tItem,setTItem]=useState(""),[tQty,setTQty]=useState(1),[tCost,setTCost]=useState(0),[notes,setNotes]=useState(""),[msg,setMsg]=useState(""),[erro,setErro]=useState("");
 async function load(){const[u,i,m]=await Promise.all([supabase.from("erp_units").select("id,name,type").eq("active",true),supabase.from("erp_stock_items").select("id,name,item_type,unit_measure,minimum_stock,average_cost").eq("active",true).order("name"),supabase.from("erp_stock_movements").select("id,unit_id,item_id,movement_type,quantity,movement_date").order("movement_date",{ascending:false}).limit(5000)]);const f=u.error||i.error||m.error;if(f)throw f;setUnits((u.data??[]) as Unit[]);setItems((i.data??[]) as Item[]);setMoves((m.data??[]) as Move[])}
 useEffect(()=>{load().catch(e=>setErro(e.message))},[]);
 const balances=useMemo(()=>{const map=new Map<string,number>();moves.forEach(m=>{const k=`${m.unit_id}:${m.item_id}`;const signed=(incoming.has(m.movement_type)?1:-1)*Number(m.quantity||0);map.set(k,(map.get(k)||0)+signed)});return map},[moves]);
 async function saveItem(e:FormEvent){e.preventDefault();setErro("");const{error}=await supabase.from("erp_stock_items").insert({name,item_type:itemType,unit_measure:measure.toUpperCase(),minimum_stock:min,average_cost:cost});if(error)setErro(error.message);else{setMsg("Item de estoque cadastrado.");setName("");await load()}}
 async function transfer(e:FormEvent){e.preventDefault();setErro("");const{error}=await supabase.rpc("erp_transfer_matriz_resgate",{p_item_id:tItem,p_quantity:tQty,p_unit_cost:tCost,p_notes:notes||null});if(error)setErro(error.message);else{setMsg("Transferência Matriz → Resgate concluída e registrada.");setTQty(1);setNotes("");await load()}}
 const uname=(id:string)=>units.find(u=>u.id===id)?.name??"—";const iname=(id:string)=>items.find(i=>i.id===id)?.name??"—";
 return <AppShell><div className="topbar"><div><h1>Estoque</h1><div className="subtitle">Saldos separados por unidade e movimentações rastreáveis.</div></div></div>{erro&&<div className="notice error">{erro}</div>}{msg&&<div className="notice success">{msg}</div>}
 <form className="form-card" onSubmit={saveItem}><h2>Novo item</h2><div className="form-grid"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Tipo<select value={itemType} onChange={e=>setItemType(e.target.value)}><option value="input">Insumo</option><option value="packaging">Embalagem</option><option value="resale">Revenda</option><option value="finished">Produto pronto</option></select></label><label>Unidade de medida<input value={measure} onChange={e=>setMeasure(e.target.value)}/></label><label>Estoque mínimo<input type="number" min="0" step="0.001" value={min} onChange={e=>setMin(Number(e.target.value))}/></label><label>Custo médio<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label></div><div className="actions"><button className="button">Cadastrar item</button></div></form>
 <form className="form-card" onSubmit={transfer}><h2>Transferir Matriz → Resgate</h2><div className="form-grid"><label>Item<select value={tItem} onChange={e=>{setTItem(e.target.value);const i=items.find(x=>x.id===e.target.value);if(i)setTCost(Number(i.average_cost||0))}} required><option value="">Selecione</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Quantidade<input type="number" min="0.001" step="0.001" value={tQty} onChange={e=>setTQty(Number(e.target.value))}/></label><label>Custo de transferência<input type="number" min="0" step="0.01" value={tCost} onChange={e=>setTCost(Number(e.target.value))}/></label><label>Observação<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="actions"><button className="button">Concluir transferência</button></div></form>
 <section className="section"><div className="section-head"><h2>Saldos atuais</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Item</th>{units.map(u=><th key={u.id}>{u.name}</th>)}<th>Mínimo</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.name}</strong><div className="metric-note">{i.unit_measure}</div></td>{units.map(u=><td key={u.id}>{(balances.get(`${u.id}:${i.id}`)||0).toFixed(3)}</td>)}<td>{Number(i.minimum_stock||0).toFixed(3)}</td></tr>)}</tbody></table>{!items.length&&<div className="empty">Cadastre o primeiro item de estoque.</div>}</div></section>
 <section className="section"><div className="section-head"><h2>Movimentações recentes</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Unidade</th><th>Item</th><th>Tipo</th><th>Quantidade</th></tr></thead><tbody>{moves.slice(0,50).map(m=><tr key={m.id}><td>{new Date(m.movement_date).toLocaleString("pt-BR")}</td><td>{uname(m.unit_id)}</td><td>{iname(m.item_id)}</td><td>{m.movement_type}</td><td>{incoming.has(m.movement_type)?"+":"-"}{Number(m.quantity).toFixed(3)}</td></tr>)}</tbody></table></div></section></AppShell>
}
