"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import AppShell from "@/components/AppShell";
import {supabase} from "@/lib/supabase";

type Opt={id:string;name:string};
type Item=Opt&{unit_measure?:string;average_cost?:number};
type Purchase={id:string;purchase_date:string;document_number:string|null;total_amount:number;payment_status:string;unit_id:string;supplier_id:string|null};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);

export default function Compras(){
 const[units,setUnits]=useState<Opt[]>([]),[suppliers,setSuppliers]=useState<Opt[]>([]),[items,setItems]=useState<Item[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]);
 const[unitId,setUnitId]=useState(""),[supplierId,setSupplierId]=useState(""),[stockId,setStockId]=useState(""),[qty,setQty]=useState(1),[cost,setCost]=useState(0),[doc,setDoc]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[status,setStatus]=useState("paid"),[msg,setMsg]=useState(""),[erro,setErro]=useState("");
 async function load(){const[u,s,i,p]=await Promise.all([supabase.from("erp_units").select("id,name").eq("active",true).order("name"),supabase.from("erp_suppliers").select("id,name").eq("active",true).order("name"),supabase.from("erp_stock_items").select("id,name,unit_measure,average_cost").eq("active",true).order("name"),supabase.from("erp_purchases").select("id,purchase_date,document_number,total_amount,payment_status,unit_id,supplier_id").order("purchase_date",{ascending:false}).limit(100)]);const f=u.error||s.error||i.error||p.error;if(f)throw f;setUnits((u.data??[]) as Opt[]);setSuppliers((s.data??[]) as Opt[]);setItems((i.data??[]) as Item[]);setPurchases((p.data??[]) as Purchase[]);if(!unitId&&u.data?.[0])setUnitId(u.data[0].id)}
 useEffect(()=>{load().catch(e=>setErro(e.message))},[]);
 const total=useMemo(()=>Number(qty||0)*Number(cost||0),[qty,cost]);
 async function save(e:FormEvent){e.preventDefault();setErro("");setMsg("");if(!unitId||!supplierId||!stockId||qty<=0){setErro("Informe unidade, fornecedor, item e quantidade.");return}const{data:auth}=await supabase.auth.getUser();const{data:p,error}=await supabase.from("erp_purchases").insert({unit_id:unitId,supplier_id:supplierId,purchase_date:date,document_number:doc||null,total_amount:total,payment_status:status,responsible_user:auth.user?.id??null}).select("id").single();if(error){setErro(error.message);return}const a=await supabase.from("erp_purchase_items").insert({purchase_id:p.id,stock_item_id:stockId,quantity:qty,unit_cost:cost});if(a.error){setErro(a.error.message);return}const m=await supabase.from("erp_stock_movements").insert({unit_id:unitId,item_id:stockId,movement_type:"purchase_in",quantity:qty,unit_cost:cost,origin_type:"purchase",origin_id:p.id,responsible_user:auth.user?.id??null});if(m.error){setErro(m.error.message);return}setMsg("Compra registrada e estoque atualizado.");setDoc("");setQty(1);setCost(0);setStockId("");await load()}
 const supplierName=(id:string|null)=>suppliers.find(x=>x.id===id)?.name??"—";const unitName=(id:string)=>units.find(x=>x.id===id)?.name??"—";
 return <AppShell><div className="topbar"><div><h1>Compras</h1><div className="subtitle">Compras geram entrada rastreável no estoque.</div></div></div>
 <form className="form-card" onSubmit={save}><h2>Nova compra</h2><div className="form-grid"><label>Unidade<select value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Selecione</option>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Fornecedor<select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Selecione</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Item de estoque<select value={stockId} onChange={e=>{setStockId(e.target.value);const i=items.find(x=>x.id===e.target.value);if(i)setCost(Number(i.average_cost||0))}}><option value="">Selecione</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Quantidade<input type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Custo unitário<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Documento<input value={doc} onChange={e=>setDoc(e.target.value)}/></label><label>Pagamento<select value={status} onChange={e=>setStatus(e.target.value)}><option value="paid">Pago</option><option value="pending">Pendente</option></select></label></div><div className="metric-value">{brl(total)}</div>{erro&&<div className="notice error">{erro}</div>}{msg&&<div className="notice success">{msg}</div>}<div className="actions"><button className="button">Registrar compra</button></div></form>
 <section className="section"><div className="section-head"><h2>Histórico</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Documento</th><th>Fornecedor</th><th>Unidade</th><th>Status</th><th>Total</th></tr></thead><tbody>{purchases.map(p=><tr key={p.id}><td>{new Date(p.purchase_date+"T12:00:00").toLocaleDateString("pt-BR")}</td><td>{p.document_number||"—"}</td><td>{supplierName(p.supplier_id)}</td><td>{unitName(p.unit_id)}</td><td>{p.payment_status}</td><td><strong>{brl(Number(p.total_amount))}</strong></td></tr>)}</tbody></table>{!purchases.length&&<div className="empty">Nenhuma compra registrada.</div>}</div></section></AppShell>
}
