"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import AppShell from "@/components/AppShell";
import {supabase} from "@/lib/supabase";

type Product={id:string;name:string;category:string|null;sale_unit:string;origin:string;cost:number;suggested_price:number;current_price:number;active:boolean;stock_item_id:string|null};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function Produtos(){
 const[list,setList]=useState<Product[]>([]),[search,setSearch]=useState("");const[name,setName]=useState(""),[category,setCategory]=useState(""),[unit,setUnit]=useState("UN"),[origin,setOrigin]=useState("resale"),[cost,setCost]=useState(0),[price,setPrice]=useState(0),[msg,setMsg]=useState(""),[erro,setErro]=useState("");
 async function load(){const{data,error}=await supabase.from("erp_products").select("id,name,category,sale_unit,origin,cost,suggested_price,current_price,active,stock_item_id").order("name");if(error)throw error;setList((data??[]) as Product[])}
 useEffect(()=>{load().catch(e=>setErro(e.message))},[]);
 const filtered=useMemo(()=>list.filter(p=>[p.name,p.category||"",p.origin].join(" ").toLowerCase().includes(search.toLowerCase())),[list,search]);
 async function save(e:FormEvent){e.preventDefault();setErro("");setMsg("");const{data:item,error:ierr}=await supabase.from("erp_stock_items").insert({name,item_type:origin==="produced"?"finished":"resale",unit_measure:unit.toUpperCase(),minimum_stock:0,average_cost:cost}).select("id").single();if(ierr){setErro(ierr.message);return}const{error}=await supabase.from("erp_products").insert({name,category:category||null,sale_unit:unit.toUpperCase(),origin,cost,suggested_price:price,current_price:price,stock_item_id:item.id});if(error){setErro(error.message);return}setMsg("Produto cadastrado e vinculado ao estoque.");setName("");setCategory("");setCost(0);setPrice(0);await load()}
 async function toggle(p:Product){const{error}=await supabase.from("erp_products").update({active:!p.active}).eq("id",p.id);if(error)setErro(error.message);else await load()}
 return <AppShell><div className="topbar"><div><h1>Produtos</h1><div className="subtitle">Produtos produzidos e itens de revenda, com vínculo automático ao estoque.</div></div></div>{erro&&<div className="notice error">{erro}</div>}{msg&&<div className="notice success">{msg}</div>}
 <form className="form-card" onSubmit={save}><h2>Novo produto</h2><div className="form-grid"><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Categoria<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Origem<select value={origin} onChange={e=>setOrigin(e.target.value)}><option value="produced">Produzido na Matriz</option><option value="resale">Revenda</option></select></label><label>Unidade<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Custo<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label>Preço atual<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label></div><div className="actions"><button className="button">Cadastrar produto</button></div></form>
 <section className="section"><div className="section-head"><h2>Produtos cadastrados</h2><input style={{maxWidth:380}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar produto..."/></div><div className="table-wrap"><table className="table"><thead><tr><th>Produto</th><th>Origem</th><th>Categoria</th><th>Custo</th><th>Venda</th><th>Margem</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filtered.map(p=>{const c=Number(p.cost||0),v=Number(p.current_price||0),m=c>0?((v-c)/c)*100:0;return <tr key={p.id}><td><strong>{p.name}</strong><div className="metric-note">{p.sale_unit}</div></td><td>{p.origin==="produced"?"Produzido":"Revenda"}</td><td>{p.category||"—"}</td><td>{brl(c)}</td><td>{brl(v)}</td><td>{m.toFixed(1)}%</td><td>{p.active?"Ativo":"Inativo"}</td><td><button className="button ghost" onClick={()=>toggle(p)}>{p.active?"Desativar":"Ativar"}</button></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty">Nenhum produto cadastrado.</div>}</div></section></AppShell>
}
