"use client";
import {FormEvent,useEffect,useState} from "react";
import AppShell from "@/components/AppShell";
import {supabase} from "@/lib/supabase";

type Unit={id:string;name:string};type Employee={id:string;name:string;unit_id:string;role_name:string|null;status:string};type Entry={id:string;employee_id:string;entry_type:string;amount:number;entry_date:string;status:string};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function Pessoas(){
 const[units,setUnits]=useState<Unit[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[entries,setEntries]=useState<Entry[]>([]);const[name,setName]=useState(""),[unit,setUnit]=useState(""),[role,setRole]=useState(""),[employeeId,setEmployeeId]=useState(""),[entryType,setEntryType]=useState("advance"),[amount,setAmount]=useState(0),[notes,setNotes]=useState(""),[msg,setMsg]=useState(""),[erro,setErro]=useState("");
 async function load(){const[u,e,x]=await Promise.all([supabase.from("erp_units").select("id,name").eq("active",true).order("name"),supabase.from("erp_employees").select("id,name,unit_id,role_name,status").order("name"),supabase.from("erp_employee_entries").select("id,employee_id,entry_type,amount,entry_date,status").order("entry_date",{ascending:false}).limit(100)]);const f=u.error||e.error||x.error;if(f)throw f;setUnits((u.data??[]) as Unit[]);setEmployees((e.data??[]) as Employee[]);setEntries((x.data??[]) as Entry[]);if(!unit&&u.data?.[0])setUnit(u.data[0].id)}
 useEffect(()=>{load().catch(e=>setErro(e.message))},[]);
 async function saveEmployee(e:FormEvent){e.preventDefault();setErro("");const{error}=await supabase.from("erp_employees").insert({name,unit_id:unit,role_name:role||null,status:"active"});if(error)setErro(error.message);else{setMsg("Funcionário cadastrado.");setName("");setRole("");await load()}}
 async function saveEntry(e:FormEvent){e.preventDefault();setErro("");const emp=employees.find(x=>x.id===employeeId);if(!emp){setErro("Selecione um funcionário.");return}const{error}=await supabase.from("erp_employee_entries").insert({employee_id:employeeId,unit_id:emp.unit_id,entry_type:entryType,amount,entry_date:new Date().toISOString().slice(0,10),status:"pending",notes:notes||null});if(error)setErro(error.message);else{setMsg("Lançamento do funcionário registrado.");setAmount(0);setNotes("");await load()}}
 const uname=(id:string)=>units.find(x=>x.id===id)?.name??"—";const ename=(id:string)=>employees.find(x=>x.id===id)?.name??"—";const label=(t:string)=>t==="advance"?"Adiantamento":t==="store_credit"?"Compra na nota":"Desconto";
 return <AppShell><div className="topbar"><div><h1>Pessoas</h1><div className="subtitle">Funcionários, compras na nota e adiantamentos.</div></div></div>{erro&&<div className="notice error">{erro}</div>}{msg&&<div className="notice success">{msg}</div>}
 <form className="form-card" onSubmit={saveEmployee}><h2>Novo funcionário</h2><div className="form-grid"><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Unidade<select value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Função<input value={role} onChange={e=>setRole(e.target.value)}/></label></div><div className="actions"><button className="button">Cadastrar funcionário</button></div></form>
 <form className="form-card" onSubmit={saveEntry}><h2>Novo lançamento</h2><div className="form-grid"><label>Funcionário<select required value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Selecione</option>{employees.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Tipo<select value={entryType} onChange={e=>setEntryType(e.target.value)}><option value="advance">Adiantamento/vale</option><option value="store_credit">Compra na nota</option><option value="deduction">Desconto</option></select></label><label>Valor<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Observação<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="actions"><button className="button">Registrar</button></div></form>
 <section className="section"><div className="section-head"><h2>Funcionários</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Nome</th><th>Unidade</th><th>Função</th><th>Status</th></tr></thead><tbody>{employees.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{uname(x.unit_id)}</td><td>{x.role_name||"—"}</td><td>{x.status}</td></tr>)}</tbody></table>{!employees.length&&<div className="empty">Nenhum funcionário cadastrado.</div>}</div></section>
 <section className="section"><div className="section-head"><h2>Lançamentos</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Funcionário</th><th>Tipo</th><th>Status</th><th>Valor</th></tr></thead><tbody>{entries.map(x=><tr key={x.id}><td>{new Date(x.entry_date+"T12:00:00").toLocaleDateString("pt-BR")}</td><td>{ename(x.employee_id)}</td><td>{label(x.entry_type)}</td><td>{x.status}</td><td>{brl(Number(x.amount))}</td></tr>)}</tbody></table></div></section></AppShell>
}
