"use client";
import {FormEvent,useEffect,useState} from "react";
import AppShell from "@/components/AppShell";
import {supabase} from "@/lib/supabase";

type Unit={id:string;name:string};type Product={id:string;name:string;current_price:number};type Order={id:string;customer_name:string;customer_contact:string|null;pickup_unit_id:string;pickup_at:string;total_amount:number;deposit_amount:number;status:string;notes:string|null};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function Encomendas(){
 const[units,setUnits]=useState<Unit[]>([]),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]);const[customer,setCustomer]=useState(""),[contact,setContact]=useState(""),[unit,setUnit]=useState(""),[pickup,setPickup]=useState(""),[productId,setProductId]=useState(""),[description,setDescription]=useState(""),[qty,setQty]=useState(1),[unitPrice,setUnitPrice]=useState(0),[deposit,setDeposit]=useState(0),[notes,setNotes]=useState(""),[msg,setMsg]=useState(""),[erro,setErro]=useState("");
 async function load(){const[u,p,o]=await Promise.all([supabase.from("erp_units").select("id,name").eq("active",true).order("name"),supabase.from("erp_products").select("id,name,current_price").eq("active",true).order("name"),supabase.from("erp_orders").select("id,customer_name,customer_contact,pickup_unit_id,pickup_at,total_amount,deposit_amount,status,notes").order("pickup_at",{ascending:true}).limit(100)]);const f=u.error||p.error||o.error;if(f)throw f;setUnits((u.data??[]) as Unit[]);setProducts((p.data??[]) as Product[]);setOrders((o.data??[]) as Order[]);if(!unit&&u.data?.[0])setUnit(u.data[0].id)}
 useEffect(()=>{load().catch(e=>setErro(e.message))},[]);
 async function save(e:FormEvent){e.preventDefault();setErro("");const total=qty*unitPrice;const{data:o,error}=await supabase.from("erp_orders").insert({customer_name:customer,customer_contact:contact||null,pickup_unit_id:unit,pickup_at:pickup,total_amount:total,deposit_amount:deposit,status:"confirmed",notes:notes||null}).select("id").single();if(error){setErro(error.message);return}const x=await supabase.from("erp_order_items").insert({order_id:o.id,product_id:productId||null,description:description||products.find(p=>p.id===productId)?.name||"Encomenda",quantity:qty,unit_price:unitPrice});if(x.error)setErro(x.error.message);else{setMsg("Encomenda registrada.");setCustomer("");setContact("");setProductId("");setDescription("");setQty(1);setUnitPrice(0);setDeposit(0);setNotes("");await load()}}
 async function setStatus(id:string,status:string){const{error}=await supabase.from("erp_orders").update({status}).eq("id",id);if(error)setErro(error.message);else await load()}
 const uname=(id:string)=>units.find(x=>x.id===id)?.name??"—";
 return <AppShell><div className="topbar"><div><h1>Encomendas</h1><div className="subtitle">Agenda, sinal, retirada e acompanhamento por status.</div></div></div>{erro&&<div className="notice error">{erro}</div>}{msg&&<div className="notice success">{msg}</div>}
 <form className="form-card" onSubmit={save}><h2>Nova encomenda</h2><div className="form-grid"><label>Cliente<input required value={customer} onChange={e=>setCustomer(e.target.value)}/></label><label>Contato<input value={contact} onChange={e=>setContact(e.target.value)}/></label><label>Retirada<select value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Data e hora<input required type="datetime-local" value={pickup} onChange={e=>setPickup(e.target.value)}/></label><label>Produto<select value={productId} onChange={e=>{setProductId(e.target.value);const p=products.find(x=>x.id===e.target.value);if(p){setDescription(p.name);setUnitPrice(Number(p.current_price||0))}}}><option value="">Personalizado</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Descrição<input required value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Quantidade<input type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Preço unitário<input type="number" min="0" step="0.01" value={unitPrice} onChange={e=>setUnitPrice(Number(e.target.value))}/></label><label>Sinal<input type="number" min="0" step="0.01" value={deposit} onChange={e=>setDeposit(Number(e.target.value))}/></label><label>Observação<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="metric-value">Total {brl(qty*unitPrice)}</div><div className="actions"><button className="button">Registrar encomenda</button></div></form>
 <section className="section"><div className="section-head"><h2>Agenda</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Retirada</th><th>Cliente</th><th>Unidade</th><th>Total</th><th>Saldo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{new Date(o.pickup_at).toLocaleString("pt-BR")}</td><td><strong>{o.customer_name}</strong><div className="metric-note">{o.customer_contact||""}</div></td><td>{uname(o.pickup_unit_id)}</td><td>{brl(Number(o.total_amount))}</td><td>{brl(Number(o.total_amount)-Number(o.deposit_amount))}</td><td>{o.status}</td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="button ghost" onClick={()=>setStatus(o.id,"in_production")}>Produção</button><button className="button ghost" onClick={()=>setStatus(o.id,"ready")}>Pronta</button><button className="button ghost" onClick={()=>setStatus(o.id,"delivered")}>Entregue</button></div></td></tr>)}</tbody></table>{!orders.length&&<div className="empty">Nenhuma encomenda registrada.</div>}</div></section></AppShell>
}
