"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowDownRight,ArrowUpRight,WalletCards} from "lucide-react";
import AppShell from "@/components/AppShell";
import {supabase} from "@/lib/supabase";
type Opt={id:string;name:string};type Entry={id:string;unit_id:string;entry_type:string;amount:number;competence_date:string;due_date:string|null;status:string;notes:string|null};type Rev={id:string;unit_id:string;revenue_date:string;cash:number;pix:number;debit:number;credit:number;delivery:number;others:number};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);const statusLabel=(s:string)=>({forecast:"Previsto",partial:"Parcial",paid:"Pago",received:"Recebido",overdue:"Vencido",cancelled:"Cancelado"}[s]||s);const typeLabel=(s:string)=>({expense:"Despesa",income:"Receita",payable:"Conta a pagar",receivable:"Conta a receber"}[s]||s);
export default function Financeiro(){
 const[units,setUnits]=useState<Opt[]>([]),[entries,setEntries]=useState<Entry[]>([]),[revs,setRevs]=useState<Rev[]>([]);const[unit,setUnit]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10));const[cash,setCash]=useState(0),[pix,setPix]=useState(0),[debit,setDebit]=useState(0),[credit,setCredit]=useState(0),[delivery,setDelivery]=useState(0),[others,setOthers]=useState(0);const[type,setType]=useState("expense"),[amount,setAmount]=useState(0),[due,setDue]=useState(""),[notes,setNotes]=useState(""),[msg,setMsg]=useState(""),[erro,setErro]=useState("");
 async function load(){const[u,e,r]=await Promise.all([supabase.from("erp_units").select("id,name").eq("active",true).order("name"),supabase.from("erp_financial_entries").select("id,unit_id,entry_type,amount,competence_date,due_date,status,notes").order("competence_date",{ascending:false}).limit(100),supabase.from("erp_daily_revenue").select("id,unit_id,revenue_date,cash,pix,debit,credit,delivery,others").order("revenue_date",{ascending:false}).limit(60)]);const f=u.error||e.error||r.error;if(f)throw f;setUnits((u.data??[]) as Opt[]);setEntries((e.data??[]) as Entry[]);setRevs((r.data??[]) as Rev[]);if(!unit&&u.data?.[0])setUnit(u.data[0].id)}useEffect(()=>{load().catch(e=>setErro(e.message))},[]);
 const revenueTotal=useMemo(()=>revs.reduce((s,r)=>s+[r.cash,r.pix,r.debit,r.credit,r.delivery,r.others].reduce((a,b)=>a+Number(b||0),0),0),[revs]);const expenses=useMemo(()=>entries.filter(e=>e.entry_type==="expense"&&e.status==="paid").reduce((s,e)=>s+Number(e.amount||0),0),[entries]);const pending=useMemo(()=>entries.filter(e=>["forecast","partial","overdue"].includes(e.status)).reduce((s,e)=>s+Number(e.amount||0),0),[entries]);const overdue=useMemo(()=>entries.filter(e=>e.status==="overdue"||(["forecast","partial"].includes(e.status)&&e.due_date&&new Date(e.due_date+"T23:59:59")<new Date())).length,[entries]);const daily=cash+pix+debit+credit+delivery+others;
 async function saveRevenue(e:FormEvent){e.preventDefault();setErro("");setMsg("");const{data:a}=await supabase.auth.getUser();const{error}=await supabase.from("erp_daily_revenue").upsert({unit_id:unit,revenue_date:date,cash,pix,debit,credit,delivery,others,responsible_user:a.user?.id??null},{onConflict:"unit_id,revenue_date"});if(error)setErro(error.message);else{setMsg("Faturamento diário salvo com sucesso.");await load()}}
 async function saveEntry(e:FormEvent){e.preventDefault();setErro("");setMsg("");const{data:a}=await supabase.auth.getUser();const{error}=await supabase.from("erp_financial_entries").insert({unit_id:unit,entry_type:type,amount,competence_date:date,due_date:due||null,status:"forecast",notes:notes||null,responsible_user:a.user?.id??null});if(error)setErro(error.message);else{setMsg("Lançamento financeiro salvo com sucesso.");setAmount(0);setDue("");setNotes("");await load()}}
 const name=(id:string)=>units.find(x=>x.id===id)?.name??"—";
 return <AppShell><div className="topbar page-hero"><div><span className="eyebrow">Controle financeiro</span><h1>Financeiro</h1><div className="subtitle">Fechamento diário, receitas, despesas e compromissos das duas unidades.</div></div><div className="hero-chip"><WalletCards size={18}/><div><span>Resultado simples</span><strong>{brl(revenueTotal-expenses)}</strong></div></div></div>{erro&&<div className="notice error">{erro}</div>}{msg&&<div className="notice success">{msg}</div>}
 <section className="grid4"><div className="card metric-card primary"><div className="metric-icon"><ArrowUpRight size={17}/></div><div className="metric-label">Faturamento</div><div className="metric-value">{brl(revenueTotal)}</div><div className="metric-note">Total registrado</div></div><div className="card metric-card"><div className="metric-icon"><ArrowDownRight size={17}/></div><div className="metric-label">Despesas pagas</div><div className="metric-value">{brl(expenses)}</div><div className="metric-note">Efetivadas</div></div><div className="card metric-card"><div className="metric-label">Pendências</div><div className="metric-value">{brl(pending)}</div><div className="metric-note">Previstas, parciais ou vencidas</div></div><div className={`card metric-card ${overdue?"attention":""}`}><div className="metric-icon"><AlertTriangle size={17}/></div><div className="metric-label">Contas vencidas</div><div className="metric-value">{overdue}</div><div className="metric-note">Exigem atenção</div></div></section>
 <form className="form-card featured-form" onSubmit={saveRevenue}><div className="form-card-head"><div><span className="eyebrow">Fechamento</span><h2>Faturamento diário</h2></div><div className="form-total"><span>Total do dia</span><strong>{brl(daily)}</strong></div></div><div className="form-grid"><label>Unidade<select value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Dinheiro<input type="number" step="0.01" min="0" value={cash} onChange={e=>setCash(Number(e.target.value))}/></label><label>Pix<input type="number" step="0.01" min="0" value={pix} onChange={e=>setPix(Number(e.target.value))}/></label><label>Débito<input type="number" step="0.01" min="0" value={debit} onChange={e=>setDebit(Number(e.target.value))}/></label><label>Crédito<input type="number" step="0.01" min="0" value={credit} onChange={e=>setCredit(Number(e.target.value))}/></label><label>Delivery<input type="number" step="0.01" min="0" value={delivery} onChange={e=>setDelivery(Number(e.target.value))}/></label><label>Outros<input type="number" step="0.01" min="0" value={others} onChange={e=>setOthers(Number(e.target.value))}/></label></div><div className="actions"><button className="button">Salvar fechamento</button></div></form>
 <form className="form-card" onSubmit={saveEntry}><div className="form-card-head"><div><span className="eyebrow">Contas e movimentos</span><h2>Novo lançamento</h2></div></div><div className="form-grid"><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="expense">Despesa</option><option value="income">Receita</option><option value="payable">Conta a pagar</option><option value="receivable">Conta a receber</option></select></label><label>Valor<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Vencimento<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Observação<input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="actions"><button className="button">Salvar lançamento</button></div></form>
 <section className="section"><div className="section-head"><div><h2>Lançamentos recentes</h2><div className="subtitle">Histórico financeiro para conferência rápida.</div></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Unidade</th><th>Tipo</th><th>Status</th><th>Valor</th></tr></thead><tbody>{entries.map(x=><tr key={x.id}><td>{new Date(x.competence_date+"T12:00:00").toLocaleDateString("pt-BR")}</td><td>{name(x.unit_id)}</td><td>{typeLabel(x.entry_type)}</td><td><span className={`badge ${x.status==="paid"||x.status==="received"?"ok":x.status==="overdue"?"danger":"warning"}`}>{statusLabel(x.status)}</span></td><td><strong>{brl(Number(x.amount))}</strong></td></tr>)}</tbody></table>{!entries.length&&<div className="empty">Nenhum lançamento financeiro ainda.</div>}</div></section></AppShell>}
